version: '2'
services:
  myerp.db:
    image: postgres:9.4
    ports:
      - "127.0.0.1:9032:5432"
    network_mode: bridge
    volumes:
#      - "./data/db:/var/lib/postgresql/data"
       - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      
